theme: jekyll-theme-modernist
title: Carol Ballantine
description: Independent researcher, teacher and writer. I am interested in migration, refugee rights, gender, identities and the politics of emotion. PhD 2020 NUI Galway
